package com.dataSwitch.base.bean;

import java.util.Date;

public class DatabaseConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DS_ID
     *
     * @mbggenerated
     */
    private Long dsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DS_NAME
     *
     * @mbggenerated
     */
    private String dsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DS_FLAG
     *
     * @mbggenerated
     */
    private String dsFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DB_DRIVER
     *
     * @mbggenerated
     */
    private String dbDriver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DB_NAME
     *
     * @mbggenerated
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DB_HOST
     *
     * @mbggenerated
     */
    private String dbHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DB_PORT
     *
     * @mbggenerated
     */
    private Integer dbPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.DB_SCHEMA
     *
     * @mbggenerated
     */
    private String dbSchema;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.LAST_MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.MIN_SIZE
     *
     * @mbggenerated
     */
    private Integer minSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATABASE_CONFIG.MAX_SIZE
     *
     * @mbggenerated
     */
    private Integer maxSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DS_ID
     *
     * @return the value of DATABASE_CONFIG.DS_ID
     *
     * @mbggenerated
     */
    public Long getDsId() {
        return dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DS_ID
     *
     * @param dsId the value for DATABASE_CONFIG.DS_ID
     *
     * @mbggenerated
     */
    public void setDsId(Long dsId) {
        this.dsId = dsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DS_NAME
     *
     * @return the value of DATABASE_CONFIG.DS_NAME
     *
     * @mbggenerated
     */
    public String getDsName() {
        return dsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DS_NAME
     *
     * @param dsName the value for DATABASE_CONFIG.DS_NAME
     *
     * @mbggenerated
     */
    public void setDsName(String dsName) {
        this.dsName = dsName == null ? null : dsName.trim();
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DS_FLAG
     *
     * @return the value of DATABASE_CONFIG.DS_FLAG
     *
     * @mbggenerated
     */

    public String getDsFlag() {
        return dsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DS_FLAG
     *
     * @param dsFlag the value for DATABASE_CONFIG.DS_FLAG
     *
     * @mbggenerated
     */
    public void setDsFlag(String dsFlag) {
        this.dsFlag = dsFlag == null ? null : dsFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DB_DRIVER
     *
     * @return the value of DATABASE_CONFIG.DB_DRIVER
     *
     * @mbggenerated
     */
    public String getDbDriver() {
        return dbDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DB_DRIVER
     *
     * @param dbDriver the value for DATABASE_CONFIG.DB_DRIVER
     *
     * @mbggenerated
     */
    public void setDbDriver(String dbDriver) {
        this.dbDriver = dbDriver == null ? null : dbDriver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DB_NAME
     *
     * @return the value of DATABASE_CONFIG.DB_NAME
     *
     * @mbggenerated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DB_NAME
     *
     * @param dbName the value for DATABASE_CONFIG.DB_NAME
     *
     * @mbggenerated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.USER_NAME
     *
     * @return the value of DATABASE_CONFIG.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.USER_NAME
     *
     * @param userName the value for DATABASE_CONFIG.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.PASSWORD
     *
     * @return the value of DATABASE_CONFIG.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.PASSWORD
     *
     * @param password the value for DATABASE_CONFIG.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DB_HOST
     *
     * @return the value of DATABASE_CONFIG.DB_HOST
     *
     * @mbggenerated
     */
    public String getDbHost() {
        return dbHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DB_HOST
     *
     * @param dbHost the value for DATABASE_CONFIG.DB_HOST
     *
     * @mbggenerated
     */
    public void setDbHost(String dbHost) {
        this.dbHost = dbHost == null ? null : dbHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DB_PORT
     *
     * @return the value of DATABASE_CONFIG.DB_PORT
     *
     * @mbggenerated
     */
    public Integer getDbPort() {
        return dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DB_PORT
     *
     * @param dbPort the value for DATABASE_CONFIG.DB_PORT
     *
     * @mbggenerated
     */
    public void setDbPort(Integer dbPort) {
        this.dbPort = dbPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.DB_SCHEMA
     *
     * @return the value of DATABASE_CONFIG.DB_SCHEMA
     *
     * @mbggenerated
     */
    public String getDbSchema() {
        return dbSchema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.DB_SCHEMA
     *
     * @param dbSchema the value for DATABASE_CONFIG.DB_SCHEMA
     *
     * @mbggenerated
     */
    public void setDbSchema(String dbSchema) {
        this.dbSchema = dbSchema == null ? null : dbSchema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.STATUS
     *
     * @return the value of DATABASE_CONFIG.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.STATUS
     *
     * @param status the value for DATABASE_CONFIG.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.CREATE_TIME
     *
     * @return the value of DATABASE_CONFIG.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.CREATE_TIME
     *
     * @param createTime the value for DATABASE_CONFIG.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.LAST_MODIFY_TIME
     *
     * @return the value of DATABASE_CONFIG.LAST_MODIFY_TIME
     *
     * @mbggenerated
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.LAST_MODIFY_TIME
     *
     * @param lastModifyTime the value for DATABASE_CONFIG.LAST_MODIFY_TIME
     *
     * @mbggenerated


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.MIN_SIZE
     *
     * @return the value of DATABASE_CONFIG.MIN_SIZE
     *
     * @mbggenerated
     */
    public Integer getMinSize() {
        return minSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.MIN_SIZE
     *
     * @param minSize the value for DATABASE_CONFIG.MIN_SIZE
     *
     * @mbggenerated
     */
    public void setMinSize(Integer minSize) {
        this.minSize = minSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATABASE_CONFIG.MAX_SIZE
     *
     * @return the value of DATABASE_CONFIG.MAX_SIZE
     *
     * @mbggenerated
     */
    public Integer getMaxSize() {
        return maxSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATABASE_CONFIG.MAX_SIZE
     *
     * @param maxSize the value for DATABASE_CONFIG.MAX_SIZE
     *
     * @mbggenerated
     */
    public void setMaxSize(Integer maxSize) {
        this.maxSize = maxSize;
    }
}