package com.dataSwitch.base.bean;

import java.math.BigDecimal;
import java.util.Date;

public class DataSwitchControl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.ROW_ID
     *
     * @mbggenerated
     */
    private Long rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.SRC_DS_ID
     *
     * @mbggenerated
     */
    private Long srcDsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.START_TIME
     *
     * @mbggenerated
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.CATCH_STEP
     *
     * @mbggenerated
     */
    private Integer catchStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.FORWARD_STEP
     *
     * @mbggenerated
     */
    private Integer forwardStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.WAIT_TRANS_TIME
     *
     * @mbggenerated
     */
    private Integer waitTransTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.RETRYS
     *
     * @mbggenerated
     */
    private Integer retrys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.COMPARE_COLUMN
     *
     * @mbggenerated
     */
//    private String compareColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.RULE_ID
     *
     * @mbggenerated
     */
//    private BigDecimal ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.BATCH_FLAG
     *
     * @mbggenerated
     */
    private String batchFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.LAST_MODIFY_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_CONTROL.processing_type
     *
     * @mbggenerated
     */
//    private String processingType;


    public Long getRowId() {
        return rowId;
    }

    public void setRowId(Long rowId) {
        this.rowId = rowId;
    }

    public Long getSrcDsId() {
        return srcDsId;
    }

    public void setSrcDsId(Long srcDsId) {
        this.srcDsId = srcDsId;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public Integer getCatchStep() {
        return catchStep;
    }

    public void setCatchStep(Integer catchStep) {
        this.catchStep = catchStep;
    }

    public Integer getForwardStep() {
        return forwardStep;
    }

    public void setForwardStep(Integer forwardStep) {
        this.forwardStep = forwardStep;
    }

    public Integer getWaitTransTime() {
        return waitTransTime;
    }

    public void setWaitTransTime(Integer waitTransTime) {
        this.waitTransTime = waitTransTime;
    }

    public Integer getRetrys() {
        return retrys;
    }

    public void setRetrys(Integer retrys) {
        this.retrys = retrys;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getBatchFlag() {
        return batchFlag;
    }

    public void setBatchFlag(String batchFlag) {
        this.batchFlag = batchFlag;
    }
}