package com.dataSwitch.base.bean;

import java.util.Date;

public class DataSwitchSubControl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.ROW_ID
     *
     * @mbggenerated
     */
    private Long rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.MAIN_ID
     *
     * @mbggenerated
     */
    private Long mainId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.SOURCE_TYPE
     *
     * @mbggenerated
     */
//    private String sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.TABNAME
     *
     * @mbggenerated
     */
//    private String tabname;
    private String srcTbName;
    private String distTbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.DS_ID
     *
     * @mbggenerated
     */
    private Long dsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.ROW_COLUMN
     *
     * @mbggenerated
     */
    private String rowColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.QUERY_COLUMN
     *
     * @mbggenerated
     */
    private String queryColumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.LAST_MODIFY_TIME
     *
     * @mbggenerated
     */

    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.PRIORITY_LEVEL
     *
     * @mbggenerated
     */
    private String priorityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_SWITCH_SUB_CONTROL.START_TIME
     *
     * @mbggenerated
     */
    private String startTime;


    public Long getRowId() {
        return rowId;
    }

    public void setRowId(Long rowId) {
        this.rowId = rowId;
    }

    public Long getMainId() {
        return mainId;
    }

    public void setMainId(Long mainId) {
        this.mainId = mainId;
    }

    public String getSrcTbName() {
        return srcTbName;
    }

    public void setSrcTbName(String srcTbName) {
        this.srcTbName = srcTbName;
    }

    public String getDistTbName() {
        return distTbName;
    }

    public void setDistTbName(String distTbName) {
        this.distTbName = distTbName;
    }

    public Long getDsId() {
        return dsId;
    }

    public void setDsId(Long dsId) {
        this.dsId = dsId;
    }

    public String getQueryColumn() {
        return queryColumn;
    }

    public void setQueryColumn(String queryColumn) {
        this.queryColumn = queryColumn;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getPriorityLevel() {
        return priorityLevel;
    }

    public void setPriorityLevel(String priorityLevel) {
        this.priorityLevel = priorityLevel;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getRowColumn() {
        return rowColumn;
    }

    public void setRowColumn(String rowColumn) {
        this.rowColumn = rowColumn;
    }
}